### ISSUE TITLE
error: "IRAM_ATTR" redefined [-Werror]

### ISSUE THREAD

**Issue by amiravni** [Sermus/ESP8266_ArduinoIDE#1]
Great project! Thanks for developing this code!
I tried to use it, starting with trying to compile the "blink" example, and got the error:

In file included from C:\Arduino\hardware\Espressif\ESP8266\cores\esp8266\Sming\Sming\Wiring/../include/user_config.h:27:0,
                 from C:\Arduino\hardware\Espressif\ESP8266\cores\esp8266\Sming\Sming\Wiring/Arduino.h:6,
                 from blink.ino:3:
C:\Arduino\hardware\Espressif\ESP8266\cores\esp8266\Sming\Sming\system\include/esp_systemapi.h:21:0: error: "IRAM_ATTR" redefined [-Werror]
 #define IRAM_ATTR **attribute**((section(".iram.text")))

I'm not a code guro but on a first look it doesn't seems that the "IRAM_ATTR " is redefined. Do you have an idea why this error could happen?

**Comment by Sermus** [comment]
Hi, please download the latest version. The problem is already solved

**Comment by amiravni** [comment]
Thank you!
