### ISSUE TITLE
Trying to use SDK functions

### ISSUE THREAD

**Issue by yotamp** [Sermus/ESP8266_ArduinoIDE#3]
Hi, 
Great project!
I'm trying to use the system_deep_sleep() function (and others) from the SDK.
It succeeds to compile and upload it but doesn't seem to execute it on the chip - just goes to the next line in the code...
What should I do to make the SDK functions run properly?

**Comment by Sermus** [comment]
Hello,
I don't support this anymore.
We concentrated on https://github.com/esp8266/Arduino which is far ahead from this now. Please try.
